<?php

return [
    'lang' => 'en',
    'payments' => 'Laravel має чудову документацію, яка охоплює кожен аспект фреймворку. Незалежно від того, чи ви новачок, чи маєте попередній досвід роботи з Laravel, ми рекомендуємо прочитати нашу документацію від початку до кінця.',
    'laracasts' => 'Laracasts пропонує тисячі відеоуроків з розробки Laravel, PHP і JavaScript. Ознайомтеся з ними, переконайтеся самі та значно підвищуйте свої навички розвитку в процесі.',
    'news' => 'Новини Laravel — це портал і інформаційний бюлетень, керований спільнотою, що збирає всі останні та найважливіші новини в екосистемі Laravel, включаючи випуски нових пакетів і навчальні посібники.',
    'ecosystem' => "Laravel's robust library of first-party tools and libraries, such as <a href=\"https://forge.laravel.com\" class=\"underline hover:text-gray-700 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500\">Forge</a>, <a href=\"https://vapor.laravel.com\" class=\"underline hover:text-gray-700 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500\">Vapor</a>, <a href=\"https://nova.laravel.com\" class=\"underline hover:text-gray-700 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500\">Nova</a>, and <a href=\"https://envoyer.io\" class=\"underline hover:text-gray-700 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500\">Envoyer</a> help you take your projects to the next level. Pair them with powerful open source libraries like <a href=\"https://laravel.com/docs/billing\" class=\"underline hover:text-gray-700 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500\">Cashier</a>, <a href=\"https://laravel.com/docs/dusk\" class=\"underline hover:text-gray-700 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500\">Dusk</a>, <a href=\"https://laravel.com/docs/broadcasting\" class=\"underline hover:text-gray-700 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500\">Echo</a>, <a href=\"https://laravel.com/docs/horizon\" class=\"underline hover:text-gray-700 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500\">Horizon</a>, <a href=\"https://laravel.com/docs/sanctum\" class=\"underline hover:text-gray-700 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500\">Sanctum</a>, <a href=\"https://laravel.com/docs/telescope\" class=\"underline hover:text-gray-700 dark:hover:text-white focus:outline focus:outline-2 focus:rounded-sm focus:outline-red-500\">Telescope</a>, and more.",
];
